# Centennial College - Winter 2026
# Student: Engracia Batista
# Student Number: 301394018

spring.application.name=HockeyEurekaServer

# Eureka server runs on port 8761 by convention
server.port=8761

# Do not register the server itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
